Refactor rendering: separate app, GL core, and geometry layouts
- Move Renderer and Shader into src/gl as pure OpenGL modules
- Introduce geometry-specific GPUObject/GeometryData implementations
  for single VBO, interleaved VBO, and multiple VBO layouts
- Simplify Application to own only windowing and lifecycle logic
- Update Makefile to select geometry layout examples explicitly

This commit restructures the project to support learning-focused
experiments with different vertex data layouts while keeping
Renderer and Application responsibilities clean.

diff --git a/Code/projects/1_draw_triangle/Makefile b/Code/projects/1_draw_triangle/Makefile
--- a/Code/projects/1_draw_triangle/Makefile
+++ b/Code/projects/1_draw_triangle/Makefile
@@ -1,16 +1,74 @@
+###############################################################################
+# Makefile
+###############################################################################
 
-OPENGL_SRC =../../third_party/glad/src/glad.c
-OPENGL_INCLUDE =../../third_party/glad/include
+# --------------------------------
+# OpenGL / GLAD
+# --------------------------------
+OPENGL_SRC = ../../third_party/glad/src/glad.c
+OPENGL_HDR = ../../third_party/glad/include
 
+# --------------------------------
+# VBO selection
+# --------------------------------
+VBO_SRC :=
+VBO_HDR :=
+
+ifeq ($(VBO_OPTION), single)
+
+  VBO_SRC = src/geometry/1_singleVBO/*.cpp
+  VBO_HDR = src/geometry/1_singleVBO
+
+else ifeq ($(VBO_OPTION), interleave)
+
+  VBO_SRC = src/geometry/2_interleavedVBO/*.cpp
+  VBO_HDR = src/geometry/2_interleavedVBO
+
+else ifeq ($(VBO_OPTION), multiple)
+
+  VBO_SRC = src/geometry/3_MultipleVBOs/*.cpp
+  VBO_HDR = src/geometry/3_MultipleVBOs
+
+endif
+
+# --------------------------------
+# Sources / Includes
+# --------------------------------
 SRC = src/app/*.cpp \
-      $(OPENGL_SRC)
-INCLUDE= -I. -I$(OPENGL_INCLUDE)
+      src/gl/*.cpp  \
+      $(OPENGL_SRC) \
+      $(VBO_SRC)
 
+INCLUDES = -I. \
+           -Isrc/gl/ \
+           -I$(OPENGL_HDR) \
+           -I$(VBO_HDR)
+
+# --------------------------------
+# Targets
+# --------------------------------
+.PHONY: help all clean
+
+help:
+	@echo "Usage: make vbo-[single|interleave|multiple]"
+	@echo
+	@echo "Targets:"
+	@echo " * vbo-single"
+	@echo " * vbo-interleave"
+	@echo " * vbo-multiple"
+
+vbo-%:
+	$(MAKE) VBO_OPTION=$* all
 
 all:
+	@if [ -z "$(VBO_SRC)" ]; then \
+		echo "Error: VBO_OPTION not set or invalid"; \
+		echo "Use: make vbo-[single|interleave|multiple]"; \
+		exit 1; \
+	fi
 	mkdir -p /tmp/gl/shaders
 	cp -r ./src/shaders/* /tmp/gl/shaders/
-	g++ -std=c++20 $(SRC) $(INCLUDE) -o prog -lSDL2 -ldl
+	g++ -g -std=c++20 -Weffc++ $(SRC) $(INCLUDES) -o prog -lSDL2 -ldl
 
 clean:
 	rm -f prog
